"""
Data Extraction Functions for Bootstrap Results
================================================

Comprehensive toolkit for processing, analyzing, and visualizing bootstrap results
from HDF5 files generated by the ECHEMES bootstrapping framework.

Key Features
------------

**Data Loading:**
    - Extract confidence intervals from HDF5 files
    - Load fitted parameters from bootstrap samples
    - Automatic file discovery and batch processing
    - Support for multiple dataset formats

**Statistical Analysis:**
    - Identify varying vs. fixed parameters
    - Compute summary statistics across datasets
    - Create comprehensive parameter tables
    - MultiIndex DataFrame support for complex analyses

**Visualization:**
    - Comparison plots across multiple datasets
    - Grid layouts with one subplot per parameter
    - Individual parameter plots for detailed analysis
    - Parameter distribution histograms from bootstrap samples
    - Publication-ready figures with customizable styling

**Complete Pipeline:**
    - process_bootstrap_data() - One-function solution for complete analysis
    - Modular functions for custom workflows
    - Flexible output options (save, display, return)
    - Progress reporting and error handling

Usage Examples
--------------

**Quick Analysis (Recommended):**

.. code-block:: python

    from data_extraction_functions import process_bootstrap_data
    
    # Complete pipeline - load, analyze, visualize, save
    results = process_bootstrap_data(
        folder_path='cluster/bootstrap_data',
        save_folder='analysis_results',
        create_plots=True,
        save_plots=True,
        show_plots=False
    )

**Custom Workflow:**

.. code-block:: python

    from data_extraction_functions import (
        load_confidence_intervals,
        identify_varying_parameters,
        plot_confidence_intervals_comparison,
        create_summary_dataframe
    )
    
    # Load data
    confidence_data = load_confidence_intervals('bootstrap_data')
    varying_params = identify_varying_parameters(confidence_data)
    
    # Create specific plots
    fig = plot_confidence_intervals_comparison(
        confidence_data, varying_params,
        save_path='comparison.png'
    )
    
    # Generate summary
    summary_df = create_summary_dataframe(
        'bootstrap_data',
        save_path='summary.csv'
    )

**Accessing Individual Components:**

.. code-block:: python

    # Access specific results from process_bootstrap_data
    confidence_data = results['confidence_data']
    varying_params = results['varying_params']
    summary_df = results['summary_dataframe']
    figures = results['figures']

Function Categories
-------------------

**Data Loading:**
    - load_confidence_intervals() - Extract confidence intervals
    - load_fitted_parameters() - Extract bootstrap parameter samples

**Analysis:**
    - identify_varying_parameters() - Find non-fixed parameters
    - create_summary_dataframe() - Comprehensive parameter summary

**Visualization:**
    - plot_confidence_intervals_comparison() - Multi-dataset comparison
    - plot_confidence_intervals_grid() - Grid layout by parameter
    - create_individual_parameter_plots() - One plot per parameter
    - plot_fitted_parameters_distributions() - Bootstrap histograms

**Pipeline:**
    - process_bootstrap_data() - Complete analysis workflow

Output Structure
----------------

**Confidence Intervals:**
    Dictionary mapping dataset names to DataFrames with parameters as index
    and (lower_bound, upper_bound) as columns.

**Fitted Parameters:**
    Dictionary mapping dataset names to DataFrames with bootstrap samples as
    rows and parameters as columns.

**Summary DataFrame:**
    MultiIndex DataFrame with (Parameter, Statistic) columns containing
    Original_Fit, Lower_Bound, and Upper_Bound for each parameter across
    all datasets.

**Figures:**
    Dictionary organized by plot type:
    - 'comparison': Multi-dataset comparison figure
    - 'grid': Grid layout figure
    - 'individual': Dict of per-parameter figures
    - 'fitted_distributions': Dict of distribution figures per dataset

Notes
-----
All functions support both interactive display and file saving. Set show_plot=False
and provide save paths for batch processing without GUI dependencies.
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np


def load_confidence_intervals(folder_path, file_pattern='.h5', verbose=True):
    """
    Load confidence intervals from HDF5 files in a folder.
    
    Parameters
    ----------
    folder_path : str
        Path to folder containing HDF5 files.
    file_pattern : str, optional
        File extension pattern to match. Default is '.h5'.
    verbose : bool, optional
        Whether to print processing information. Default is True.
        
    Returns
    -------
    dict
        Dictionary mapping file labels (without .h5 extension) to confidence interval DataFrames.
        Each DataFrame has parameters as index and confidence bounds as columns.
    """
    files = [f for f in os.listdir(folder_path) if f.endswith(file_pattern)]
    confidence_data = {}
    
    for file in files:
        with pd.HDFStore(f'{folder_path}/{file}', 'r') as store:
            if verbose:
                print(f"\n--- Processing {file} ---")
            
            confidence_intervals = store['confidence_intervals']
            
            if verbose:
                print("DataFrame shape:", confidence_intervals.shape)
                print("DataFrame columns:", confidence_intervals.columns.tolist())
                print("DataFrame index:", confidence_intervals.index.tolist())
                print(confidence_intervals)
            
            label = file.replace('.h5', '')
            confidence_data[label] = confidence_intervals
    
    if verbose:
        print("\nConfidence data structure:")
        for label, df in confidence_data.items():
            print(f"{label}: {df.shape}")
        
    return confidence_data


def identify_varying_parameters(confidence_data):
    """
    Identify parameters that vary across datasets (not fixed).
    
    Parameters
    ----------
    confidence_data : dict
        Dictionary of confidence interval DataFrames from load_confidence_intervals.
        
    Returns
    -------
    list of str
        List of parameter names that have varying values (lower bound != upper bound)
        across any dataset in the collection.
    """
    if not confidence_data:
        return []
        
    first_dataset = list(confidence_data.values())[0]
    all_params = first_dataset.index.tolist()
    
    # Filter out parameters that are fixed (lower bound == upper bound)
    varying_params = []
    for param in all_params:
        for data in confidence_data.values():
            if param in data.index:
                lower = data.loc[param, 0]  # Column 0 = lower bound
                upper = data.loc[param, 1]  # Column 1 = upper bound
                if lower != upper:  # Parameter varies
                    varying_params.append(param)
                    break
    
    return list(set(varying_params))  # Remove duplicates


def plot_confidence_intervals_comparison(confidence_data, varying_params, save_path=None, ylim=(0, 50), show_plot=True):
    """
    Create comparison plot of confidence intervals across datasets.
    
    Parameters
    ----------
    confidence_data : dict
        Dictionary of confidence interval DataFrames from load_confidence_intervals.
    varying_params : list of str
        List of parameter names to plot.
    save_path : str, optional
        Path to save the plot. If None, plot is not saved to file. Default is None.
    ylim : tuple of float, optional
        Y-axis limits for the plot as (ymin, ymax). Default is (0, 50).
    show_plot : bool, optional
        Whether to display the plot interactively. Default is True.
        
    Returns
    -------
    matplotlib.figure.Figure or None
        The created figure object, or None if no varying parameters to plot.
    """
    if not varying_params:
        print("No varying parameters to plot")
        return None
        
    fig, ax = plt.subplots(figsize=(14, 10))
    
    x_positions = np.arange(len(varying_params))
    width = 0.8 / len(confidence_data)  # Width for each dataset
    
    for i, (label, data) in enumerate(confidence_data.items()):
        means = []
        lower_errors = []
        upper_errors = []
        
        for param in varying_params:
            if param in data.index:
                lower = data.loc[param, 0]  # Column 0 => lower bound
                upper = data.loc[param, 1]  # Column 1 => upper bound
                mean = (lower + upper) / 2
                means.append(mean)
                lower_errors.append(mean - lower)
                upper_errors.append(upper - mean)
            else:
                means.append(0)
                lower_errors.append(0)
                upper_errors.append(0)
        
        # Offset x positions for each dataset
        x_offset = x_positions + (i - len(confidence_data)/2 + 0.5) * width
        
        # Plot error bars
        ax.errorbar(x_offset, means, yerr=[lower_errors, upper_errors], 
                   label=label, marker='o', capsize=5, capthick=2, 
                   linewidth=2, markersize=6, fmt='o')
    
    ax.set_xlabel('Parameters')
    ax.set_ylabel('Parameter Values')
    ax.set_title('Confidence Intervals Comparison Across Datasets')
    ax.set_xticks(x_positions)
    ax.set_xticklabels(varying_params, rotation=45, ha='right')
    ax.set_ylim(ylim)
    ax.legend()
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"Saved comparison plot to {save_path}")
    
    if show_plot:
        plt.show()
    
    return fig


def plot_confidence_intervals_grid(confidence_data, varying_params, save_path=None, show_plot=True):
    """
    Create grid plot of confidence intervals - one subplot per parameter.
    
    Parameters
    ----------
    confidence_data : dict
        Dictionary of confidence interval DataFrames from load_confidence_intervals.
    varying_params : list of str
        List of parameter names to plot.
    save_path : str, optional
        Path to save the plot. If None, plot is not saved to file. Default is None.
    show_plot : bool, optional
        Whether to display the plot interactively. Default is True.
        
    Returns
    -------
    matplotlib.figure.Figure or None
        The created figure object, or None if no varying parameters to plot.
    """
    if not varying_params:
        print("No varying parameters to plot")
        return None
        
    # Create grid of subplots - one for each parameter
    n_params = len(varying_params)
    n_cols = min(3, n_params)  # Max 3 columns
    n_rows = (n_params + n_cols - 1) // n_cols
    
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(5*n_cols, 4*n_rows))
    if n_params == 1:
        axes = [axes]
    elif n_rows == 1:
        axes = axes.reshape(1, -1)
    axes = axes.flatten()
    
    # Get dataset names for x-axis
    dataset_names = list(confidence_data.keys())
    x_pos = np.arange(len(dataset_names))
    
    for idx, param in enumerate(varying_params):
        ax = axes[idx]
        
        # Collect data for this parameter across all datasets
        means = []
        lower_errors = []
        upper_errors = []
        
        for label, data in enumerate(confidence_data.items()):
            label_name, data_df = data
            if param in data_df.index:
                lower = data_df.loc[param, 0]
                upper = data_df.loc[param, 1]
                mean = (lower + upper) / 2
                means.append(mean)
                lower_errors.append(mean - lower)
                upper_errors.append(upper - mean)
            else:
                means.append(0)
                lower_errors.append(0)
                upper_errors.append(0)
        
        # Plot error bars
        ax.errorbar(x_pos, means, yerr=[lower_errors, upper_errors], 
                   marker='o', capsize=5, capthick=2, linewidth=2, markersize=8, fmt='o')
        
        # Adjust y-limits to handle outliers
        if means:
            mean_vals = np.array(means)
            valid_means = mean_vals[mean_vals != 0]  # Exclude zeros (missing data)
            
            if len(valid_means) > 0:
                q75, q25 = np.percentile(valid_means, [75, 25])
                iqr = q75 - q25
                upper_limit = q75 + 1.5 * iqr
                
                max_val = np.max(valid_means)
                min_val = np.min(valid_means)
                
                if max_val > upper_limit:
                    lower_limit = min(min_val * 0.95, q25 - 0.5 * iqr)
                    ax.set_ylim(lower_limit, upper_limit)
                    
                    # Add text annotation about clipped values
                    ax.text(0.02, 0.98, f'Clipped at {upper_limit:.3f}', 
                           transform=ax.transAxes, va='top', ha='left', 
                           bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7),
                           fontsize=8)
        
        ax.set_title(f'{param}', fontsize=12, fontweight='bold')
        ax.set_xticks(x_pos)
        ax.set_xticklabels(dataset_names, rotation=45, ha='right')
        ax.grid(True, alpha=0.3)
        
        # Add value labels on the plot (only if not clipped)
        for i, (mean, lower_err, upper_err) in enumerate(zip(means, lower_errors, upper_errors)):
            if mean != 0:  # Only label non-zero values
                y_text = mean + upper_err
                # Check if the text would be within the plot bounds
                if ax.get_ylim()[1] > y_text:
                    ax.text(i, y_text + (max(means) - min(means)) * 0.05 if max(means) != min(means) else 0.1, 
                           f'{mean:.3f}', ha='center', va='bottom', fontsize=8)
    
    # Hide unused subplots
    for idx in range(n_params, len(axes)):
        axes[idx].set_visible(False)
    
    plt.suptitle('Parameter Confidence Intervals by Dataset', fontsize=16, fontweight='bold')
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"Saved grid plot to {save_path}")
    
    if show_plot:
        plt.show()
    
    return fig


def create_individual_parameter_plots(confidence_data, varying_params, save_folder=None):
    """
    Create individual plots for each parameter.
    
    Parameters
    ----------
    confidence_data : dict
        Dictionary of confidence interval DataFrames from load_confidence_intervals.
    varying_params : list of str
        List of parameter names to plot.
    save_folder : str, optional
        Folder path to save individual plots. If None, plots are not saved.
        Folder is created if it doesn't exist. Default is None.
        
    Returns
    -------
    dict
        Dictionary mapping parameter names to their matplotlib figure objects.
    """
    figures = {}
    
    if save_folder:
        os.makedirs(save_folder, exist_ok=True)
    
    print("\n--- Creating individual parameter plots ---")
    
    for param in varying_params:
        # Create single plot for this parameter
        fig, ax = plt.subplots(figsize=(10, 6))
        
        # Collect data for this parameter across all datasets
        dataset_names = []
        means = []
        lower_errors = []
        upper_errors = []
        
        for label, data in confidence_data.items():
            if param in data.index:
                dataset_names.append(label)
                lower = data.loc[param, 0]
                upper = data.loc[param, 1]
                mean = (lower + upper) / 2
                means.append(mean)
                lower_errors.append(mean - lower)
                upper_errors.append(upper - mean)
        
        if means:  # Only plot if we have data
            x_pos = np.arange(len(dataset_names))
            
            # Plot error bars
            ax.errorbar(x_pos, means, yerr=[lower_errors, upper_errors], 
                       marker='o', capsize=5, capthick=2, linewidth=2, markersize=8, fmt='o')
            
            ax.set_title(f'Confidence Intervals: {param}', fontsize=14, fontweight='bold')
            ax.set_xlabel('Dataset')
            ax.set_ylabel('Parameter Value')
            ax.set_xticks(x_pos)
            ax.set_xticklabels(dataset_names, rotation=45, ha='right')
            ax.grid(True, alpha=0.3)
            
            # Add value labels
            for i, (mean, lower_err, upper_err) in enumerate(zip(means, lower_errors, upper_errors)):
                ax.text(i, mean + upper_err + (max(means) - min(means)) * 0.05 if max(means) != min(means) else 0.1, 
                       f'{mean:.3f}', ha='center', va='bottom', fontsize=10, fontweight='bold')
        
        plt.tight_layout()
        
        if save_folder:
            save_path = f'{save_folder}/{param}_confidence_intervals.png'
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Saved plot for {param} to {save_path}")
        
        plt.close()  # Close the figure to save memory
        figures[param] = fig

    print(f"\nCreated individual plots for {len(varying_params)} parameters")
    return figures


def load_fitted_parameters(folder_path, file_pattern='.h5', verbose=True):
    """
    Load fitted parameters from bootstrap samples in HDF5 files.
    
    Parameters
    ----------
    folder_path : str
        Path to folder containing HDF5 files.
    file_pattern : str, optional
        File extension pattern to match. Default is '.h5'.
    verbose : bool, optional
        Whether to print processing information. Default is True.
        
    Returns
    -------
    dict
        Dictionary mapping file labels to fitted parameters DataFrames.
        Each DataFrame has bootstrap samples as rows and parameters as columns.
    """
    files = [f for f in os.listdir(folder_path) if f.endswith(file_pattern)]
    fitted_params_data = {}
    
    if verbose:
        print("\n--- Extracting fitted parameters from bootstrap samples ---")
    
    for file in files:
        with pd.HDFStore(f'{folder_path}/{file}', 'r') as store:
            label = file.replace('.h5', '')
            
            # Find all fitted_params keys (e.g., fitted_params/s1, fitted_params/s2, etc.)
            fitted_keys = [k for k in store.keys() if k.startswith('/fitted_params/')]
            
            if fitted_keys:
                if verbose:
                    print(f"Found {len(fitted_keys)} bootstrap samples for {label}")
                
                # Collect all fitted parameters for this dataset
                all_fitted_params = []
                for key in fitted_keys:
                    params_series = store[key]
                    all_fitted_params.append(params_series.to_dict())
                
                # Convert to DataFrame
                fitted_df = pd.DataFrame(all_fitted_params)
                fitted_params_data[label] = fitted_df
                
                if verbose:
                    print(f"Parameters shape for {label}: {fitted_df.shape}")
                    print(f"Parameters: {fitted_df.columns.tolist()}")
    
    return fitted_params_data


def plot_fitted_parameters_distributions(fitted_params_data, varying_params, save_folder=None, show_plots=True):
    """
    Plot distributions of fitted parameters from bootstrap samples.
    
    Parameters
    ----------
    fitted_params_data : dict
        Dictionary of fitted parameters DataFrames from load_fitted_parameters.
        Each DataFrame has bootstrap samples as rows and parameters as columns.
    varying_params : list of str
        List of parameter names to plot distributions for.
    save_folder : str, optional
        Folder path to save plots. If None, plots are not saved.
        Folder is created if it doesn't exist. Default is None.
    show_plots : bool, optional
        Whether to display plots interactively. Default is True.
        
    Returns
    -------
    dict
        Dictionary mapping dataset labels to their matplotlib figure objects.
        Returns empty dict if no fitted parameters data or no varying parameters found.
    """
    figures = {}
    
    if not fitted_params_data:
        print("No fitted parameters data found")
        return figures
    
    if save_folder:
        os.makedirs(save_folder, exist_ok=True)
    
    # Filter to only varying parameters
    fitted_varying_params = []
    first_fitted_dataset = list(fitted_params_data.values())[0]
    for param in first_fitted_dataset.columns.tolist():
        if param in varying_params:
            fitted_varying_params.append(param)
    
    if not fitted_varying_params:
        print("No varying fitted parameters found to plot")
        return figures
    
    # Create plots for each dataset
    for dataset_label, current_fitted_dataset in fitted_params_data.items():
        n_fitted_params = len(fitted_varying_params)
        n_cols_fitted = min(3, n_fitted_params)
        n_rows_fitted = (n_fitted_params + n_cols_fitted - 1) // n_cols_fitted
        
        fig_fitted, axes_fitted = plt.subplots(n_rows_fitted, n_cols_fitted, 
                                              figsize=(5*n_cols_fitted, 4*n_rows_fitted))
        if n_fitted_params == 1:
            axes_fitted = [axes_fitted]
        elif n_rows_fitted == 1:
            axes_fitted = axes_fitted.reshape(1, -1)
        axes_fitted = axes_fitted.flatten()
        
        for idx, param in enumerate(fitted_varying_params):
            ax = axes_fitted[idx]
            
            if param in current_fitted_dataset.columns:
                # Plot histogram/distribution of fitted values
                values = current_fitted_dataset[param].dropna()
                weights = np.ones_like(values) / len(values)  # Normalize to form a probability density
                ax.hist(values, alpha=0.6, color='blue', 
                       bins=min(20, len(values)//2), density=False, weights=weights)
            
            ax.set_title(f'{param} Distribution', fontsize=12, fontweight='bold')
            ax.set_xlabel('Parameter Value')
            ax.set_ylabel('Density')
            ax.grid(True, alpha=0.3)
        
        # Hide unused subplots
        for idx in range(n_fitted_params, len(axes_fitted)):
            axes_fitted[idx].set_visible(False)
        
        plt.suptitle(f'Fitted Parameters Distributions - {dataset_label}', 
                   fontsize=16, fontweight='bold')
        plt.tight_layout()
        
        if save_folder:
            save_path = f'{save_folder}/fitted_parameters_distributions_{dataset_label}.png'
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Saved fitted parameters plot for {dataset_label} to {save_path}")
        
        if show_plots:
            plt.show()
        else:
            plt.close()
        
        figures[dataset_label] = fig_fitted
    
    print(f"\nPlotted fitted parameters distributions for {len(fitted_params_data)} datasets")
    print(f"Fitted varying parameters: {fitted_varying_params}")
    
    return figures


def create_summary_dataframe(folder_path, file_pattern='.h5', save_path=None):
    """
    Create summary DataFrame with first fit parameters and confidence intervals.
    
    Parameters
    ----------
    folder_path : str
        Path to folder containing HDF5 files.
    file_pattern : str, optional
        File extension pattern to match. Default is '.h5'.
    save_path : str, optional
        Path to save the summary CSV file. If None, file is not saved.
        Default is None.
        
    Returns
    -------
    pandas.DataFrame
        Summary DataFrame with MultiIndex columns (Parameter, Statistic).
        Rows are dataset names. Columns include Original_Fit, Lower_Bound,
        and Upper_Bound for each parameter.
    """
    files = [f for f in os.listdir(folder_path) if f.endswith(file_pattern)]
    
    print("\n--- Creating summary DataFrame with MultiIndex ---")
    
    datasets = []
    parameters = set()
    data_dict = {}
    
    for file in files:
        with pd.HDFStore(f'{folder_path}/{file}', 'r') as store:
            label = file.replace('.h5', '')
            datasets.append(label)
            
            first_fit_params = store['first_fit_params']
            confidence_intervals = store['confidence_intervals']
            
            data_dict[label] = {}
            
            for param_name in first_fit_params.index:
                parameters.add(param_name)
                data_dict[label][param_name] = {
                    'Original_Fit': first_fit_params.loc[param_name],
                    'Lower_Bound': confidence_intervals.loc[param_name, 0] if param_name in confidence_intervals.index else None,
                    'Upper_Bound': confidence_intervals.loc[param_name, 1] if param_name in confidence_intervals.index else None
                }
    
    # Create MultiIndex DataFrame
    parameters = sorted(list(parameters))
    
    # Create MultiIndex columns: (parameter, statistic)
    multi_columns = pd.MultiIndex.from_product([parameters, ['Original_Fit', 'Lower_Bound', 'Upper_Bound']], 
                                              names=['Parameter', 'Statistic'])
    
    summary_df = pd.DataFrame(index=datasets, columns=multi_columns)
    
    for dataset in datasets:
        for param in parameters:
            if param in data_dict[dataset]:
                summary_df.at[dataset, (param, 'Original_Fit')] = data_dict[dataset][param]['Original_Fit']
                summary_df.at[dataset, (param, 'Lower_Bound')] = data_dict[dataset][param]['Lower_Bound']
                summary_df.at[dataset, (param, 'Upper_Bound')] = data_dict[dataset][param]['Upper_Bound']
    
    print("\nSummary DataFrame with MultiIndex:")
    print(summary_df)
    
    if save_path:
        summary_df.to_csv(save_path)
        print(f"\nSaved summary to {save_path}")
    
    return summary_df


def process_bootstrap_data(folder_path='cluster/new_bootstrap_data', save_folder='processed_data', 
                          create_plots=True, save_plots=True, show_plots=True):
    """
    Complete processing pipeline for bootstrap data extraction and visualization.
    
    This is the main convenience function that orchestrates all data extraction,
    analysis, and visualization steps in a single call.
    
    Parameters
    ----------
    folder_path : str, optional
        Path to folder containing HDF5 files with bootstrap results.
        Default is 'cluster/new_bootstrap_data'.
    save_folder : str, optional
        Folder path to save processed results and plots.
        Created if it doesn't exist. Default is 'processed_data'.
    create_plots : bool, optional
        Whether to create visualization plots. Default is True.
    save_plots : bool, optional
        Whether to save plots to files. Default is True.
    show_plots : bool, optional
        Whether to display plots interactively. Default is True.
        
    Returns
    -------
    dict
        Dictionary containing all processed data and results with keys:
        - 'confidence_data' : dict of confidence interval DataFrames
        - 'varying_params' : list of varying parameter names
        - 'fitted_params_data' : dict of fitted parameters DataFrames
        - 'summary_dataframe' : pandas DataFrame with summary statistics
        - 'figures' : dict of matplotlib figure objects organized by plot type
    """
    # Create save folder
    if save_plots and save_folder:
        os.makedirs(save_folder, exist_ok=True)
    
    # Load confidence intervals
    print("Loading confidence intervals...")
    confidence_data = load_confidence_intervals(folder_path)
    
    if not confidence_data:
        print("No confidence interval data found")
        return {}
    
    # Identify varying parameters
    varying_params = identify_varying_parameters(confidence_data)
    print(f"Found varying parameters: {varying_params}")
    
    results = {
        'confidence_data': confidence_data,
        'varying_params': varying_params,
        'figures': {}
    }
    
    if create_plots and varying_params:
        # Create comparison plot
        comp_save_path = f'{save_folder}/confidence_intervals_comparison.png' if save_plots else None
        fig_comp = plot_confidence_intervals_comparison(
            confidence_data, varying_params, 
            save_path=comp_save_path, show_plot=show_plots
        )
        results['figures']['comparison'] = fig_comp
        
        # Create grid plot
        grid_save_path = f'{save_folder}/confidence_intervals_grid.png' if save_plots else None
        fig_grid = plot_confidence_intervals_grid(
            confidence_data, varying_params,
            save_path=grid_save_path, show_plot=show_plots
        )
        results['figures']['grid'] = fig_grid
        
        # Create individual parameter plots
        if save_plots:
            individual_figures = create_individual_parameter_plots(
                confidence_data, varying_params, save_folder
            )
            results['figures']['individual'] = individual_figures
    
    # Load and process fitted parameters
    print("\nLoading fitted parameters...")
    fitted_params_data = load_fitted_parameters(folder_path)
    results['fitted_params_data'] = fitted_params_data
    
    if create_plots and fitted_params_data:
        # Create fitted parameters distribution plots
        fitted_figures = plot_fitted_parameters_distributions(
            fitted_params_data, varying_params,
            save_folder=save_folder if save_plots else None,
            show_plots=show_plots
        )
        results['figures']['fitted_distributions'] = fitted_figures
    
    # Create summary DataFrame
    print("\nCreating summary DataFrame...")
    summary_save_path = f'{save_folder}/parameter_summary_multiindex.csv' if save_plots else None
    summary_df = create_summary_dataframe(folder_path, save_path=summary_save_path)
    results['summary_dataframe'] = summary_df
    
    print(f"\n--- Processing Complete ---")
    print(f"Processed {len(confidence_data)} datasets")
    print(f"Found {len(varying_params)} varying parameters")
    if save_plots:
        print(f"Results saved to {save_folder}/")
    
    return results


# Example usage and main execution
if __name__ == "__main__":
    # Run the complete processing pipeline
    results = process_bootstrap_data(
        folder_path='cluster/new_bootstrap_data',
        save_folder='processed_data',
        create_plots=True,
        save_plots=True,
        show_plots=True
    )
    
    # Access individual results
    confidence_data = results.get('confidence_data', {})
    varying_params = results.get('varying_params', [])
    summary_df = results.get('summary_dataframe')
    
    print(f"\nProcessed {len(confidence_data)} datasets with {len(varying_params)} varying parameters")